language: perl

matrix:
  include:
  - perl: "5.30"
  - perl: "5.26"
  - perl: "5.22"
  - perl: "5.20"
    dist: trusty

install:
  - "cpanm -n --quiet --installdeps --with-develop ."

after_success:
  - "cover -test -report coveralls"
  - "cover -test -report kritika"

notifications:
  email: false
