language: perl

perl: [ "5.20", "5.22", "5.24", "5.26" ]

install:
  - "cpanm -n --quiet --installdeps --with-develop ."

after_success:
  - "cover -test -report coveralls"
  - "cover -test -report kritika"

notifications:
  email: false
