language: perl

perl: [ "5.20", "5.22", "5.24", "5.26" ]

env:
  global:
  - KRITIKA_TOKEN=c4e7a7be452711f4e9628b1b31623025019eaf9d

install:
  - "cpanm -n --quiet --installdeps --with-develop ."

after_success:
  - "cover -test -report coveralls"
  - "cover -test -report kritika"

notifications:
  email: false
